server:
  port: 0
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: someuser
    password: somepass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.index.html

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/